Update Makefile
 from dbus/dbus_client.cpp:1:
libsigc++>=2.5.1 requires "-std=c++11" compiler flag with cmake

Compile fail with

/usr/include/c++/5.5.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

Fix : Adding -std=c++11 to the compiler flags